# Generated by Django 3.2.23 on 2024-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_addtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='none', max_length=20)),
                ('coin_ids', models.ManyToManyField(to='website.Product')),
            ],
        ),
    ]
