# Generated by Django 3.2.23 on 2024-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_addtocart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=1000000000, null=True),
        ),
    ]
