# Generated by Django 3.2.23 on 2024-04-11 12:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000000000, null=True)),
                ('last_name', models.CharField(max_length=1000000000, null=True)),
                ('bank_name', models.CharField(max_length=1000000000, null=True)),
                ('account_no', models.CharField(max_length=1000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=1000000000, null=True)),
                ('wallet_address', models.CharField(max_length=1000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.CharField(default='none', max_length=20)),
                ('confirmation_no', models.CharField(max_length=1000000000, null=True)),
                ('payment_proof', models.ImageField(null=True, upload_to='media')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True)),
                ('first_name', models.CharField(max_length=1000000000, null=True)),
                ('last_name', models.CharField(max_length=1000000000, null=True)),
                ('email', models.CharField(max_length=1000000000, null=True)),
                ('phone_no', models.CharField(max_length=1000000000, null=True)),
                ('address', models.CharField(max_length=1000000000, null=True)),
                ('country', models.CharField(max_length=1000000000, null=True)),
                ('postal_code', models.CharField(max_length=1000000000, null=True)),
                ('coin_ids', models.ManyToManyField(to='website.Product')),
            ],
        ),
        migrations.CreateModel(
            name='discount_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=1000000000, null=True)),
                ('order_limit', models.IntegerField(null=True)),
                ('user_ids', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
