# Generated by Django 3.2.23 on 2024-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Unfulfilled', 'Unfulfilled')], max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=1000000000, null=True),
        ),
    ]
