# Generated by Django 3.2.23 on 2024-04-21 11:39

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20240412_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_material_authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=1000000000, null=True)),
                ('email', models.CharField(max_length=1000000000, null=True)),
                ('phone', models.CharField(max_length=1000000000, null=True)),
                ('order_no', models.CharField(max_length=1000000000, null=True)),
                ('notes', models.CharField(max_length=1000000000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=ckeditor.fields.RichTextField(default=0.21875),
            preserve_default=False,
        ),
    ]
